import React from 'react';
import ReactDOM from 'react-dom';
import Header from './components/header/header.jsx';
import App from './components/Card/3--app.jsx';
import Plus from './components/plusplus/apl.jsx';
import Form from './components/form/form.jsx';
import List from './components/ToDoList/list.jsx';
ReactDOM.render(< Header/>, document.getElementById('root'));
ReactDOM.render(< App/>, document.getElementById('cont'));
ReactDOM.render(< Plus/>, document.getElementById('plus'));
ReactDOM.render(< Form/>, document.getElementById('form'));
ReactDOM.render(< List/>, document.getElementById('List'));